services:
  django:
    build: ./back
    image: django-app:1.0.0
    ports:
      - 127.0.0.1:8000:8000
  
  web:
    build: ./front
    image: react-app:1.0.0
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - django